# File Creation
REPORTS_PATH = "./reports"
RESULTS_PATH = "./results"
RESULT_FILE_NAME_SUFFIX = "RESULT"

# Thresholds for report evaluation
RSSI_EXCLNT_GOOD_BOUND = -59
RSSI_GOOD_FAIR_BOUND = -69
RSSI_FAIR_POOR_BOUND = -74
RSSI_POOR_UNUSBL_BOUND = -79

RSRP_EXCLNT_GOOD_BOUND = -79
RSRP_GOOD_FAIR_BOUND = -89
RSRP_FAIR_POOR_BOUND = -109
RSRP_POOR_UNUSBL_BOUND = -119

RSRQ_EXCLNT_GOOD_BOUND = -5
RSRQ_GOOD_FAIR_BOUND = -8
RSRQ_FAIR_POOR_BOUND = -10
RSRQ_POOR_UNUSBL_BOUND = -19
